# create review
POST http://localhost:3000/create
Content-Type: application/json

{
    "place_id": 2,
    "user_id": 1,
    "weekly_salary": 1400.0,
    "shift_days_count": 6,
    "shift_duration": 8
}

# list reviews
GET http://localhost:3000/reviews

# create place
POST http://localhost:3000/places
Content-Type: application/json

{
    "name": "Biolento_",
    "address": "C. Gral. San Martín 350, Col Americana, Obrera, 44140 Guadalajara, Jal."
}

# list places
GET http://localhost:3000/places


# protected test1
GET http://localhost:3000/protected
Authorization: "Bearer chapalo conche tu mare"


# login
GET http://localhost:3000/login
